# Generated by Django 3.0.7 on 2020-07-01 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postulantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.?\\d{3}\\.?\\d{3}[-]?[0-9kK]{1}$')])),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=75)),
                ('vigente', models.BooleanField(default=True)),
                ('f_postulacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
